### PR TITLE
rename controlers.go to controllers.go

### LINKED ISSUE #10: Rename `controlers.go` to `controllers.go`
**Task description**:
There is a typo in the name of file `app/controlers.go`. We'd better rename it to `controllers.go`.

**Solution**:
Rename `controlers.go` to `controllers.go`

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by lowang-bh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #10

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Thanks a lot
/remove-kind bug
/kind cleanup

**Review by RainbowMango — COMMENTED** [review]
/lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
